/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.wwl.canvas;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

import android.graphics.Canvas;
import android.graphics.Typeface;


@Kroll.module(name="Canvas", id="com.wwl.canvas")
public class CanvasModule extends KrollModule {

	// Standard Debugging variables
	private static final String LCAT = "CanvasModule";


	// Module constants
	@Kroll.constant public static final int VERTEX_MODE_TRIANGLES = 0;
	@Kroll.constant public static final int VERTEX_MODE_TRIANGLES_FAN = 1;
	@Kroll.constant public static final int VERTEX_MODE_TRIANGLES_STRIP = 2;

	// Constructor
	public CanvasModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(LCAT, "Canvas module started");
	}
}
